global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'indoc-backend'
    static_configs:
      # scrape the locally running non-containerized backend
      - targets: ['host.docker.internal:8000']
    metrics_path: '/api/v1/metrics'
    # Refresh business metrics before each scrape
    metric_relabel_configs:
      - source_labels: [__address__]
        target_label: __tmp_pre_scrape
        action: replace
        replacement: 'update_metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'

  - job_name: 'celery'
    static_configs:
      - targets: ['flower:5555']
    metrics_path: '/metrics'