"""Add unique constraint for document title and file_type per tenant

Revision ID: 6b41d60cf269
Revises: add_multi_tenancy_001
Create Date: 2025-09-01 03:19:18.688960+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b41d60cf269'
down_revision = 'add_multi_tenancy_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_document_title_file_type_user',
        'documents',
        ['title', 'file_type', 'uploaded_by']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_title_file_type_user', 'documents', type_='unique')
    # ### end Alembic commands ###