openapi: 3.0.3
info:
  title: Database Provider API
  version: 1.0.0
servers:
  - url: /api/v1/database
paths:
  /metadata/{id}:
    get:
      summary: Get metadata for a document
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Metadata retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  metadata:
                    type: object
    put:
      summary: Update metadata for a document
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                metadata:
                  type: object
      responses:
        "200":
          description: Metadata updated
  /metadata:
    post:
      summary: Create metadata entry for a document
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                metadata:
                  type: object
      responses:
        "201":
          description: Created
    get:
      summary: List metadata entries
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
        - name: offset
          in: query
          schema:
            type: integer
      responses:
        "200":
          description: List of metadata
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-rbac: {}
