# .github/workflows/build-and-push.yml
name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker Tag
        id: docker_meta
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - name: Build and push images
        run: |
          docker buildx bake --file docker-bake.hcl \
            --set "*.tag=${{ env.TAG }}" \
            --push
        if: github.event_name != 'pull_request'

      - name: Build images for PR
        run: |
          docker buildx bake --file docker-bake.hcl \
            --set "*.tag=${{ env.TAG }}" \
            --load
        if: github.event_name == 'pull_request'
